so ~/new-workflow/vim/autoload/plug.vim

so ~/new-workflow/vim/cfg/mappings
so ~/new-workflow/vim/cfg/plugins
so ~/new-workflow/vim/cfg/options

" Plugins configs
so ~/new-workflow/vim/cfg/easymotion
so ~/new-workflow/vim/cfg/vim-javascript
