NPM_PACKAGES="${HOME}/.npm-packages"

PATH="$NPM_PACKAGES/bin:$PATH"

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/new-workflow/bash" && pwd)"
source "$DIR/alias"
source "$DIR/ps1"
source "$DIR/git-completion.bash"

. "$DIR/z.sh"

set -o vi

[ -f ~/.fzf.bash ] && source ~/.fzf.bash

export EDITOR=vi

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
