NPM_PACKAGES="${HOME}/.npm-packages"

PATH="$NPM_PACKAGES/bin:$PATH"

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/new-workflow/bash" && pwd)"
source "$DIR/alias"
source "$DIR/ps1"
fpath=(~/.zsh $fpath)

. "$DIR/z.sh"

set -o vi
